server:
  port: 8090

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

auth:
  token:
    jwtSecret: J6RzYiFgcFSOQazw7IZr0HVqM6r7SGPJ3Ke3OeuV7sg=
