spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&serverTimezone=UTC
    username: sean
    password: Sean@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

api:
  prefix: /api/v1

auth:
  token:
    jwtSecret: J6RzYiFgcFSOQazw7IZr0HVqM6r7SGPJ3Ke3OeuV7sg=
    expirationInMils: 86400000
